nomecompleto = str(input('digite seu nome completo: '))
print(nomecompleto.upper())
print(nomecompleto.lower())
print(nomecompleto.capitalize())
print(nomecompleto.title())
print(nomecompleto.split())
print(nomecompleto.swapcase())
print(nomecompleto.find("i"))
print(nomecompleto.count('a', 0, 16))
print(len(nomecompleto))
print(nomecompleto[9])
print(nomecompleto[9:3])
print(nomecompleto[9:3:5])
print(nomecompleto[9::3])
print(nomecompleto.replace('dores', 'Bittencourt de Bourbon'))
